### PR TITLE
Fix #248 delete javascript reference to released media

### LINKED ISSUE #248: References to released media objects are not cleared
# Bug Report

## Problem

Within Media.js a reference to every media object is stored in the `mediaObjects` object. When the resources are released the reference remains. This leads to a slow memory leak when many sounds are played. In our use case there are many short sounds which we play repeatedly (sometimes releasing in between), each time a new Media instance is created (even for the same sound file) a new record is added to `mediaObjects`, and never removed.

### What is expected to happen?

There is no memory footprint for released media objects.

### What does actually happen?

A small memory footprint remains

### Environment, Platform, Device

I have observed this as a problem in Android, but it impacts all platforms

### Version information
5.0.3

## Checklist

- [ X] I searched for existing GitHub issues
- [X ] I updated all Cordova tooling to most recent version
- [X ] I included all the necessary information above

I will provide a pull request shortly to address this issue.

### PR DESCRIPTION
**Pull request by AgDude**
### Platforms affected
All (www change)

### Motivation and Context
This removes the javascript reference to released media objects.  See #248 

### Description
Add a success callback to delete media id after it is released by platform specific code.

### Checklist

- [ ] I've run the tests to see all new and existing tests pass
- [NA ] I added automated test coverage as appropriate for this change
- [ NA] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [Y ] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [NA ] I've updated the documentation if necessary

### CODE REVIEW

File: www/Media.js [hunk 1]
```diff
@@ -156,7 +156,10 @@ Media.prototype.resumeRecord = function() {
  * Release the resources.
  */
 Media.prototype.release = function() {
-    exec(null, this.errorCallback, "Media", "release", [this.id]);
+    var me = this;
+    exec(function() {
+      delete mediaObjects[me.id];
```
Comment (timbru31) [inline www/Media.js:161]: We should probably use splice instead - delete won't change the length or reindexes the array.

Comment (AgDude) [reply www/Media.js:161]: `mediaObjects` is an object, not an array. It is defined on line 26.

Comment (timbru31) [reply www/Media.js:161]: Oh indeed, sorry!
